driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: debian-7
  driver:
    image: dokken/debian-7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y init-system-helpers

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
  
- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd

- name: ubuntu-17.04
  driver:
    image: dokken/ubuntu-17.04
    pid_one_command: /bin/systemd
  
suites:
  - name: default
    run_list: test::default
